/**
 * Exact DeepSeek V4.1-Flash image-token arithmetic.
 *
 * Every rule in this module is a line-by-line port of the official
 * `inference/image_processor.py` published by `deepseek-ai/DeepSeek-V4.1-Flash`
 * at the pinned immutable revision recorded below. The golden fixtures in
 * `tests/fixtures/vision-golden.json` are generated by executing that official
 * implementation, so any change here must keep the Node counts byte-identical
 * to the reference output.
 *
 * The V4.1 revision replaced the previous vision arithmetic wholesale: the
 * position-dependent alignment padding (`COMPRESS_PAD_TO`, the odd-row pad and
 * the final two-token alignment pad) is gone, `safe_resize` is a single pass
 * instead of a budget loop, and the aspect-ratio clamp is inert because the
 * official config pins `vision_max_wh_ratio` to `null`. The block length is now
 * exactly `nLlmH * (nLlmW + 1) + 2` and does not depend on the absolute
 * serialized position.
 *
 * These arithmetic results back intrinsic-grid estimates, never exact counts
 * of the final request. The official expansion depends on the adapter's final
 * request-image projection — including per-route pixel-budget or image-detail
 * overrides and byte-cap reprojection — none of which is published through a
 * public API, and a projected image can count FEWER tokens than its intrinsic
 * grid suggests. The measurement layer therefore labels image-bearing nodes
 * as estimates and keeps them outside exact rewrite proofs; the 640,000-pixel
 * budget below documents the adapter default rather than establishing
 * exactness.
 */

/** Official projection parameters pinned from the V4.1-Flash repository config. */
export const DEEPSEEK_VISION_PROJECTION = Object.freeze({
  sourceRepository: 'deepseek-ai/DeepSeek-V4.1-Flash',
  sourceRevision: 'dba1be0a40aa45a94ad051997016db3960a90277',
  /** `vision_config.patch_size` from the official config. */
  visionPatchSize: 14,
  /** `vision_config.downsample_ratio` from the official config. */
  visionDownsampleRatio: 3,
  /** `vision_config.max_image_tokens`: post-preprocessing cap per image, not a fixed value. */
  visionMaxNTokens: 1024,
  /** `vision_config.min_pixels`: tiny images are upscaled before patching. */
  visionMinPixels: 295_936,
  /**
   * `vision_config.max_wh_ratio` is `null` in the official V4.1 config, so the
   * aspect-ratio clamp branch in `plan_image_grid`/`load_image` is never taken.
   * It is modelled as `undefined` and guarded with an explicit nullish test:
   * the guard must never degrade into a tautology such as `width >= 0`.
   */
  visionMaxWhRatio: undefined as number | undefined,
  /**
   * Default per-image pixel budget used by the DeepSeek adapter's normal
   * attachment projection (`DEFAULT_REQUEST_IMAGE_PIXEL_BUDGET` in
   * `@deepseek-ai/dsh-llm-deepseek`). Route overrides remain unobservable to
   * this estimator. This is NOT the server-side ~1300x1300 resize budget.
   */
  requestImagePixelBudget: 640_000,
})

/**
 * Fallback charged when durable image metadata cannot be evaluated. It sits
 * near the middle of the official 1024-token image budget so one malformed or
 * provider-projected image never makes the surrounding surface unmeasurable.
 */
export const DEEPSEEK_VISION_DEFAULT_IMAGE_TOKENS = 256

/** Stable identity for the deliberately approximate image-token counter. */
export const DEEPSEEK_VISION_IMAGE_ESTIMATOR = Object.freeze({
  id: `${DEEPSEEK_VISION_PROJECTION.sourceRepository}/image-token-estimate`,
  revision: `${DEEPSEEK_VISION_PROJECTION.sourceRevision}:v1`,
})

/** Aligner-grid facts the official pipeline derives from one image. */
export interface DeepSeekVisionImageGrid {
  readonly nLlmH: number
  readonly nLlmW: number
  readonly bestHeight: number
  readonly bestWidth: number
}

/**
 * One bounded estimate over the image's intrinsic grid.
 *
 * Under V4.1 the block length is position-independent, so there is no
 * alignment-residue spread to bound: `paddingMinimumTokens` and
 * `paddingMaximumTokens` are both the same block length when the source is
 * `intrinsic-grid`.
 */
export interface DeepSeekVisionImageTokenEstimate {
  readonly tokens: number
  readonly upperBoundTokens: number
  readonly source: 'intrinsic-grid' | 'default'
  readonly paddingMinimumTokens?: number
  readonly paddingMaximumTokens?: number
}

/**
 * Whether one image's intrinsic metadata fits the adapter's documented
 * default request pixel budget. This is informational only: estimation also
 * accepts larger valid dimensions because the official processor enforces its
 * own 1024-token grid budget.
 */
export function isWithinDeepSeekRequestPixelBudget(width: number, height: number): boolean {
  return width > 0 && height > 0 && width * height <= DEEPSEEK_VISION_PROJECTION.requestImagePixelBudget
}

/**
 * Expand one image into its official token count at a given stream position.
 *
 * Under V4.1 the count is position-independent: `startTokenPos` is retained
 * only to keep the exported signature and call graph stable, and does not
 * affect the result.
 */
export function deepSeekVisionImageTokens(width: number, height: number, startTokenPos: number): number {
  const grid = deepSeekVisionImageGrid(width, height)
  return deepSeekVisionImageBlockTokens(grid.nLlmH, grid.nLlmW, startTokenPos)
}

/**
 * Estimate one image without claiming an exact serialized position or final
 * adapter projection. Valid intrinsic dimensions use the official block length;
 * invalid or unsafe metadata uses the documented fixed fallback. In both cases
 * the official per-image budget is retained as a conservative upper bound.
 */
export function estimateDeepSeekVisionImageTokens(
  width: number,
  height: number,
): DeepSeekVisionImageTokenEstimate {
  if (!Number.isSafeInteger(width) || !Number.isSafeInteger(height)
    || width <= 0 || height <= 0 || !Number.isSafeInteger(width * height)) {
    return Object.freeze({
      tokens: DEEPSEEK_VISION_DEFAULT_IMAGE_TOKENS,
      upperBoundTokens: DEEPSEEK_VISION_PROJECTION.visionMaxNTokens,
      source: 'default',
    })
  }
  try {
    const grid = deepSeekVisionImageGrid(width, height)
    const tokens = deepSeekVisionImageBlockTokens(grid.nLlmH, grid.nLlmW, 0)
    return Object.freeze({
      tokens,
      upperBoundTokens: DEEPSEEK_VISION_PROJECTION.visionMaxNTokens,
      source: 'intrinsic-grid',
      paddingMinimumTokens: tokens,
      paddingMaximumTokens: tokens,
    })
  } catch {
    return Object.freeze({
      tokens: DEEPSEEK_VISION_DEFAULT_IMAGE_TOKENS,
      upperBoundTokens: DEEPSEEK_VISION_PROJECTION.visionMaxNTokens,
      source: 'default',
    })
  }
}

/**
 * Resolve the aligner grid for one image's intrinsic dimensions.
 *
 * Port of the arithmetic path of the official `plan_image_grid` plus the
 * V4.1 `safe_resize`: optional aspect-ratio clamp (inert under V4.1),
 * minimum-pixel upscale, patch-grid ceiling, and a single-pass budget solve.
 */
export function deepSeekVisionImageGrid(width: number, height: number): DeepSeekVisionImageGrid {
  const {
    visionPatchSize: patch,
    visionMaxWhRatio,
    visionMinPixels,
    visionDownsampleRatio: downsample,
    visionMaxNTokens: maxNTokens,
  } = DEEPSEEK_VISION_PROJECTION
  let effectiveWidth: number = width
  let effectiveHeight: number = height
  // Inert under V4.1 (`vision_max_wh_ratio` is null); the nullish guard keeps
  // the port faithful for any revision that does pin a ratio.
  if (visionMaxWhRatio !== undefined && visionMaxWhRatio !== null
    && effectiveWidth > effectiveHeight * visionMaxWhRatio) {
    effectiveWidth = effectiveHeight * visionMaxWhRatio
  }
  if (effectiveWidth * effectiveHeight > 0 && effectiveWidth * effectiveHeight < visionMinPixels) {
    const ratio = (visionMinPixels / (effectiveWidth * effectiveHeight)) ** 0.5
    effectiveWidth = Math.trunc(effectiveWidth * ratio)
    effectiveHeight = Math.trunc(effectiveHeight * ratio)
  }
  const bestWidth = Math.ceil(effectiveWidth / patch) * patch
  const bestHeight = Math.ceil(effectiveHeight / patch) * patch
  const resolved = safeResize(
    effectiveHeight, effectiveWidth, bestHeight, bestWidth, patch, downsample, maxNTokens,
  )
  return Object.freeze({ ...resolved })
}

/**
 * Token count of one expanded image block, port of `num_image_tokens`.
 *
 * Under V4.1 this is the WHOLE block length: `nLlmH * (nLlmW + 1)` already
 * covers one newline slot per grid row, and `+ 2` covers the start and end
 * sentinels. There is no compress pad, no odd-row pad, and no alignment pad.
 *
 * `startTokenPos` is INERT: the V4.1 block length does not depend on the
 * absolute serialized position. It is retained so the exported signature and
 * the call graph stay stable; `tests/fixtures/vision-golden.json#startPositions`
 * records the official implementation agreeing across every swept offset.
 * @internal exported for direct golden-fixture comparison.
 */
export function deepSeekVisionImageBlockTokens(nLlmH: number, nLlmW: number, startTokenPos: number): number {
  void startTokenPos
  return nLlmH * (nLlmW + 1) + 2
}

/** Port of the official `llm_grid`. */
function llmGrid(
  bestHeight: number,
  bestWidth: number,
  patch: number,
  downsample: number,
): { nLlmH: number, nLlmW: number } {
  return {
    nLlmH: Math.ceil(Math.floor(bestHeight / patch) / downsample),
    nLlmW: Math.ceil(Math.floor(bestWidth / patch) / downsample),
  }
}

/**
 * Port of the official `solve_resize_ratio` (V4.1: single solve, 2-tuple).
 *
 * The "very tall" branch is `(max_n_token - 2) // 2 * cell`, i.e. Python floor
 * division. Under the pinned V4.1 parameters `max_n_token` is always 1024, so
 * `max_n_token - 2` is always even and floor and truncation agree — the
 * `Math.floor` below is defensive fidelity, not a reachable behavioural
 * difference.
 */
function solveResizeRatio(
  height: number,
  width: number,
  patch: number,
  downsample: number,
  maxNTokens: number,
): { bestHeight: number, bestWidth: number } {
  const ratio = height / width
  const maxWFloat = Math.sqrt((maxNTokens - 2) / ratio + 0.25) - 0.5
  const maxHFloat = maxWFloat * ratio
  const cell = patch * downsample
  if (maxWFloat < 1.0) {
    // very tall: collapse to a single column
    return { bestHeight: Math.floor((maxNTokens - 2) / 2) * cell, bestWidth: cell }
  }
  if (maxHFloat < 1.0) {
    // very wide: collapse to a single row
    return { bestHeight: cell, bestWidth: (maxNTokens - 3) * cell }
  }
  const beta = Math.min(
    Math.floor(maxWFloat) * cell / width,
    Math.floor(maxHFloat) * cell / height,
  )
  return {
    bestHeight: Math.floor(height * beta / patch) * patch,
    bestWidth: Math.floor(width * beta / patch) * patch,
  }
}

/**
 * Port of the V4.1 `safe_resize`: one occupancy check and at most one solve.
 * The previous budget-decrement loop no longer exists upstream.
 *
 * Deliberate, recorded divergence from spec R2.8: the official Python carries
 * `assert num_image_tokens(n_llm_h, n_llm_w) <= max_n_token` after the solve,
 * and this port does not reproduce that assert. The bound is unreachable under
 * the pinned V4.1 parameters rather than merely unobserved —
 * `solve_resize_ratio` derives its pixel budget directly from `max_n_token`, so
 * the solved grid cannot exceed it. Independently fuzzed over 646,000 inputs (a
 * dense 1..3000 sweep plus 400,000 random sizes up to 200,000 px): zero
 * violations, worst observed block length exactly 1024, i.e. the cap itself.
 * Reproducing the assert would add a branch no test can drive, so the tradeoff
 * is recorded here instead. Re-check this if `visionMaxNTokens` is ever set to a
 * value the solver was not designed for.
 */
function safeResize(
  height: number,
  width: number,
  initialBestHeight: number,
  initialBestWidth: number,
  patch: number,
  downsample: number,
  maxNTokens: number,
): { nLlmH: number, nLlmW: number, bestHeight: number, bestWidth: number } {
  let grid = llmGrid(initialBestHeight, initialBestWidth, patch, downsample)
  let bestHeight = initialBestHeight
  let bestWidth = initialBestWidth
  if (deepSeekVisionImageBlockTokens(grid.nLlmH, grid.nLlmW, 0) > maxNTokens) {
    const solved = solveResizeRatio(height, width, patch, downsample, maxNTokens)
    bestHeight = solved.bestHeight
    bestWidth = solved.bestWidth
    grid = llmGrid(bestHeight, bestWidth, patch, downsample)
  }
  return { nLlmH: grid.nLlmH, nLlmW: grid.nLlmW, bestHeight, bestWidth }
}
